(source "gnu" "http://elpa.gnu.org/packages/")
(source "marmalade" "http://marmalade-repo.org/packages/")
(source "melpa" "http://melpa.milkbox.net/packages/")

(depends-on "cask")
(depends-on "cl-lib")
(depends-on "dash")
(depends-on "diminish")
(depends-on "epl")
(depends-on "evil")
(depends-on "evil-leader")
(depends-on "evil-nerd-commenter")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "f")
(depends-on "flycheck")
(depends-on "flycheck-haskell")
(depends-on "gh")
(depends-on "gist")
(depends-on "git")
(depends-on "git-commit-mode")
(depends-on "git-gutter-fringe+")
(depends-on "git-rebase-mode")
(depends-on "goto-chg")
(depends-on "haskell-mode")
(depends-on "load-theme-buffer-local")
(depends-on "logito")
(depends-on "magit")
(depends-on "multiple-cursors")
(depends-on "org")
(depends-on "ox-reveal")
(depends-on "pallet")
(depends-on "pcache")
(depends-on "pkg-info")
(depends-on "popwin")
(depends-on "projectile")
(depends-on "rainbow-delimiters")
(depends-on "s")
(depends-on "smartparens")
(depends-on "solarized-theme")
(depends-on "surround")
(depends-on "undo-tree")
(depends-on "yagist")
(depends-on "yasnippet")