
* Project Backlog
** Setup Emails in Emacs
:LOGBOOK:
CLOCK: [2020-04-28 Tue 00:35]--[2020-04-28 Tue 00:35] =>  0:00
:END:
*** Managing
- put newsletters into their own view and manage them as closely as
  possible from RSS feeds
**** [2020-04-23 Thu 10:14] Handling Email with Emacs – malb::blog :grasp:emacs:email:productivity:
https://martinralbrecht.wordpress.com/2016/05/30/handling-email-with-emacs/
Comment:
Thorough mu4e setup
**** [2020-04-26 Sun 09:27] mkcms/mu4e-overview: Show overview of maildir :grasp:emacs:email:productivity:
https://github.com/mkcms/mu4e-overview
Comment:
a bit like what you'd expect treemacs to be for emails
**** [2020-05-03 Sun 19:34] Ambrevar / mu4e-conversation · GitLab :grasp:emacs:email:productivity:someday:

https://gitlab.com/ambrevar/mu4e-conversation
Comment:
Something to try one day
*** Editing
- need to learn the footnote minor mode
- something to check: line breaking does weird things on the receiving end
*** Issues
**** Forwarding with org-msg
**** Can't accept outlook invite
accepting doesn't mark me as accepted in the organiser's calendar
**** TODO Can't send through M&S SMTP
** TODO Smooth windowing flow
*** [2020-04-23 Thu 10:07] nex3/perspective-el: Perspectives for Emacs. :grasp:emacs:wm:productivity:
https://github.com/nex3/perspective-el
Comment:
perspective-el seems to be the tool I need to do window layout management in Emacs the right way
*** [2020-04-23 Thu 10:08] ESS – Emacs Speaks Statistics :grasp:emacs:wm:productivity:
https://ess.r-project.org/Manual/ess.html#Controlling-buffer-display
Comment:
ESS doc has some good insights on display-buffer that is window management in Emacs
*** [2020-04-23 Thu 10:09] Dedicated Windows - GNU Emacs Lisp Reference Manual :grasp:emacs:wm:productivity:
https://www.gnu.org/software/emacs/manual/html_node/elisp/Dedicated-Windows.html#Dedicated-Windows
Comment:
bookmark on where I am in Emacs doc about window management. I should probably read that in the info straight from within Emacs :)
*** [2020-04-23 Thu 10:11] Displaying Buffers - GNU Emacs Lisp Reference Manual :grasp:emacs:wm:productivity:
https://www.gnu.org/software/emacs/manual/html_node/elisp/Displaying-Buffers.html#Displaying-Buffers
Comment:
actually that's probably a better bookmark on where I am in reading Emacs display-buffer framework for window management
*** [2020-06-13 Sat 22:40] Sergey Matsievskiy / display-buffer-control · GitLab :grasp:emacs:productivity:

https://gitlab.com/matsievskiysv/display-buffer-control
Comment:
I should probably use that. The last section of readme is compelling.
** set up org-agenda
*** TODO [#B] build *my* agenda view
Take inspiration from jethro and super-agenda
**** [2020-04-25 Sat 21:52] kidd/org-gcal.el: Org sync with Google Calendar. (active maintained project as of 2019-11-06) :grasp:emacs:productivity:calendar:
https://github.com/kidd/org-gcal.el
Comment:
for when my emails will be in Emacs and my org-agenda workflow is in my fingers
**** [2020-04-26 Sun 22:04] org mode - Defining different fonts (color) per file in org-agenda - Emacs Stack Exchange :grasp:emacs:productivity:
https://emacs.stackexchange.com/questions/23824/defining-different-fonts-color-per-file-in-org-agenda
Comment:
org-agenda views are colorless, needs fixing

**** [2020-04-26 Sun 23:40] alphapapa/org-super-agenda: Supercharge your Org daily/weekly agenda by grouping items :grasp:emacs:org-mode:productivity:
https://github.com/alphapapa/org-super-agenda

*** [2020-04-26 Sun 23:42] Improving the Agenda  :grasp:emacs:productivity:
https://llazarek.com/2018/07/improving-the-agenda.html
Comment:
various ideas that seem useful. In particular, colorful agenda view
*** [2020-04-26 Sun 23:56] Getting Boxes Done, the Code :grasp:emacs:productivity:
http://www.howardism.org/Technical/Emacs/getting-more-boxes-done.html
Comment:
another org-mode workflow, looks interesting
*** [2020-04-27 Mon 00:00] Org-Agenda as a Calendar :grasp:emacs:productivity:
https://errickson.net/org_agenda_calendar.html
Comment:
Another example of applying color to org-agenda
*** [2020-05-08 Fri 19:40] org mode - Outlook Calendar in org agenda - Emacs Stack Exchange :grasp:emacs:org-mode:productivity:

https://emacs.stackexchange.com/questions/45803/outlook-calendar-in-org-agenda
Comment:
if one day I'd want my calendar fully hosted in org-mode
*** [2020-06-17 Wed 08:01] Steffen Weinreich / msgraph-orgmode · GitLab :grasp:emacs:productivity:

https://gitlab.com/lairsdragon/msgraph-orgmode
Comment:
Download outlook calendar as org-mode file.
*** [2020-05-09 Sat 14:10] Google Calendar Synchronization :grasp:emacs:org-mode:productivity:

https://orgmode.org/worg/org-tutorials/org-google-sync.html
Comment:
google calendar <-> org-mode sync
*** [2020-05-08 Fri 19:47] kiwanami/emacs-calfw: A calendar framework for Emacs :grasp:emacs:productivity:

https://github.com/kiwanami/emacs-calfw
Comment:
A proper calendar vizz in Emacs, I am stunned.
*** [2020-05-08 Fri 20:20] insanum/gcalcli: Google Calendar Command Line Interface :grasp:emacs:org-mode:productivity:

https://github.com/insanum/gcalcli
Comment:
Could be useful for setting up calendar in org-mode
*** [2020-06-17 Wed 08:02] spegoraro/org-alert: System notifications of org agenda items :grasp:mail:emacs:productivity:

https://github.com/spegoraro/org-alert
** I want to become a writer and build a second brain
*** [2020-04-28 Tue 14:59] bnbeckwith/wc-mode: Wordcount minor mode for Emacs :grasp:emacs:blog:

https://github.com/bnbeckwith/wc-mode
Comment:
could be a useful addition to my setup for blogging and writing in Emacs
*** [2020-06-13 Sat 22:33] emacsmirror/spray: A speed reading mode :grasp:emacs:productivity:

https://github.com/emacsmirror/spray
Comment:
Speed reading in Emacs, gotta try it!
*** [2020-10-05 Mon 11:54] Top (Org-roam User Manual) :grasp:org:productivity:

https://www.orgroam.com/manual/
Comment:
Set up org-roam and start breaking mega files into small focused topics that are well inter-connected
** TODO Setup finances in an Emacs Ledger
*** [2020-04-26 Sun 23:47] Plain Text Accounting, a guide to Ledger and friends - plaintextaccounting.org :grasp:finance:emacs:
https://plaintextaccounting.org/

*** [2020-04-26 Sun 23:48] atheriel/evil-ledger: More Evil in ledger-mode. :grasp:emacs:finance:
https://github.com/atheriel/evil-ledger

*** [2020-04-26 Sun 23:56] Plain Text Accounting with ledger and ledger-likes :grasp:finance:emacs:
https://www.reddit.com/r/plaintextaccounting/

* Stuff on the radar
** [2020-05-04 Mon 23:21] Elisp Reference Sheet    :grasp:emacs:programming:

https://alhassy.github.io/ElispCheatSheet/CheatSheet.pdf
Comment:
stupendous cheat sheet for elisp
** [2020-05-08 Fri 22:38] dired-ref.pdf :grasp:emacs:productivity:

https://www.gnu.org/software/emacs/refcards/pdf/dired-ref.pdf
Comment:
To be archived for easy reference
** [2020-06-13 Sat 21:14] Using org-mode for meeting minutes • egli.dev :grasp:emacs:productivity:orgmode:

https://egli.dev/posts/using-org-mode-for-meeting-minutes/
Comment:
I need to learn more about columnview.
I should probably have a capture template for meeting minutes. Bonus point if it can be derived from PROPERTIES pertaining to meeting (e.g. attendees)
** [2020-06-13 Sat 22:51] integral-dw/org-superstar-mode: Make org-mode stars a little more super :grasp:emacs:

https://github.com/integral-dw/org-superstar-mode
Comment:
seems a more modern alternative to org-bullets
# local variables:
# eval: (anki-editor-mode +1)
# end:
** [2020-10-06 Tue 12:40] Emacs Org-mode - Export to another directory? - Stack Overflow :grasp:orgmode:

https://stackoverflow.com/questions/9559753/emacs-org-mode-export-to-another-directory
Selection:
#+begin_quote
(defun org-export-output-file-name-modified (orig-fun extension &optional subtreep pub-dir)
  (unless pub-dir
    (setq pub-dir "exported-org-files")
    (unless (file-directory-p pub-dir)
      (make-directory pub-dir)))
  (apply orig-fun extension subtreep pub-dir nil))
(advice-add 'org-export-output-file-name :around #'org-export-output-file-name-modified)
#+end_quote
Comment:
avoid clutter when you export org files
* Insipring Emacs Configs
** [2020-05-13 Wed 09:24] dot-emacs/README.org at 22f4c9dfa4de17537af8dccaba7d294382ded9e7 · zamansky/dot-emacs :grasp:emacs:productivity:

https://github.com/zamansky/dot-emacs/blob/22f4c9dfa4de17537af8dccaba7d294382ded9e7/README.org#L414
Selection:
org-msg
Comment:
c'est la Z emacs config, lots to take from starting with literate init.el
** [2020-04-26 Sun 23:32] .emacs.d/init.el at master · jethrokuan/.emacs.d :grasp:emacs:productivity:
https://github.com/jethrokuan/.emacs.d/blob/218ea42779db9d8db5dfdd6c6524abac3f10855c/init.el#L1356
Selection:
:init
  (with-eval-after-load 'flycheck
    (flycheck-add-mode 'proselint 'org-mode))
Comment:
inspiration for my agenda view
- http://irfu.cea.fr/Pisp/vianney.lebouteiller/emacs.html#orgf16d962
- https://github.com/malb/emacs.d/blob/master/malb.org
* Setup
** [2020-04-23 Thu 09:28] jeremy-compostella/org-msg :grasp:productivity:emacs:email:org:
https://github.com/jeremy-compostella/org-msg OrgMsg is a GNU/Emacs
global minor mode mixing up Org mode and Message mode to compose and
reply to emails in a Outlook HTML friendly style.

Comment: reply to emails that requires HTML using org-mode
** System / outside Emacs
*** [2020-04-28 Tue 23:07] Exim4Gmail - Debian Wiki :grasp:emacs:email:sydadmin:
https://wiki.debian.org/Exim4Gmail
Comment:
what helped me configure SMTP for mu4e

*** [2020-05-02 Sat 22:48] Fastmail setup with Emacs, mu4e and mbsync on macOS - Rakhim.org :grasp:emacs:email:productivity:

https://rakhim.org/2020/01/fastmail-setup-with-emacs-mu4e-and-mbsync-on-macos/
Selection:
mu4e-attachments-dir "~/Downloads"
Comment:
has been really useful in setting up emails in my Emacs