name: Emacs configuration test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  load-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Emacs
        run: |
          sudo apt-get update
          sudo apt-get install -y emacs-nox

      - name: Tangle literate config
        run: |
          emacs --batch -l org --eval '(org-babel-tangle-file "docs/config.org")'

      - name: Load init file
        run: |
          export HOME=$GITHUB_WORKSPACE
          emacs --batch -l init.el --eval '(message "Loaded init.el")' --kill

      - name: Run ERT smoke tests
        run: |
          export HOME=$GITHUB_WORKSPACE
          emacs --batch -l ert -l test/smoke.el -f ert-run-tests-batch-and-exit
